### PR TITLE
Merge branch 'topic/metal-sep21' into main

### PR DESCRIPTION
**Pull request by mwilsnd**
Merging the Sep. 21 feature branch back into main. `render_hillshade_layer.cpp/h` had conflicts, ensure this has been merged correctly before approving.

### CODE REVIEW

**Review by louwers — APPROVED** [review]

**Review by stefankarschti — COMMENTED** [review]
I get an [assertion here](https://github.com/maplibre/maplibre-native/blob/9ae0d8f0e41c6fc1800c32020e629a633b976cca/src/mbgl/mtl/drawable.cpp#L524C9-L524C39) after panning the map a few times with `Satellite Hybrid` style over Boston (_Metal_ flavor). It takes several style changes before reaching `Satellite Hybrid`.

On _OpenGL/drawable_ it doesn't happen.

**Comment by TimSylvester** [comment]
We ran into that one with fill, I think, when the bucket produced empty output.  But that wasn't specific to Metal.  Probably it has to do with not keeping the data around after a buffer is created for it.  I'll take a look...

**Comment by TimSylvester** [comment]
Ah, `RasterBucket` is changing the vertices and indices in the shared data, and sometimes updating them to empty, but the raster layer isn't considering that.

**Comment by TimSylvester** [comment]
Okay, I think I have that figured out.  It doesn't show up on GL because it's just not being checked, but it's still a potential problem.

It's enough that I created #1700 for it.  Unfortunately, I seem to have introduced a symbol UBO problem in the process.

**Comment by stefankarschti** [comment]
In _legacy_ code the missing indexes on raster `bucket` signals to use the raster quad (`staticDataVertices`, `staticDataIndices` & `staticDataSegments`), so a `drawable` without indexes shouldn't be created in any case.

**Review by alexcristici — APPROVED** [review]

**Review by TimSylvester — APPROVED** [review]

**Review by stefankarschti — APPROVED** [review]

**Pull request merged**
