### PR TITLE
Bazel updates

### PR DESCRIPTION
**Pull request by louwers**
- Update Bazel
- Update Bazel dependencies
- Get rid of `WORKSPACE` so Renovate can auto-update

### CODE REVIEW

**Review by keith — APPROVED** [review]
nice!

**Comment by louwers** [comment]
@keith Apparently auto-updates don't work when you have both a WORKSPACE and a MODULE.bzl. It is a miracle everything still worked. Hehe.

**Review by HarelM — APPROVED** [review]

**Comment by bdon** [comment]
Are there any guidelines on how to make this build work with MacPorts? I don't have Homebrew meaning `libuv` as defined in MODULE.bazel cannot be found.

**Comment by louwers** [comment]
@bdon You can also use CMake to build for macOS. I can write some instructions.

**Comment by bdon** [comment]
That would be really helpful. I was attempting to patch MODULE.bazel with something like this:

```
new_local_repository(
    name = "libuv",
    build_file_content = """
cc_library(
    name = "libuv",
    hdrs = [
        "include/uv.h",
        "include/uv/darwin.h",
        "include/uv/errno.h",
        "include/uv/threadpool.h",
        "include/uv/unix.h",
        "include/uv/version.h",
    ],
    srcs = [
        "lib/libuv.a",  # Static library from MacPorts
    ],
    includes = ["include"],
    visibility = ["//visibility:public"],
)
""",
    path = "/opt/local",  # MacPorts path for libuv
)
```

But haven't had any success yet.

**Comment by louwers** [comment]
The GLFW app crashes on macOS with Metal if you use CFRunLoop. I haven't been able to figure out why, that is why I changed the macOS Bazel build config to use libuv. Ideally we change it to compile libuv from source instead...

Anyway, if you the CMake build config uses CFRunLoop. As said the GLFW app crashes when used with Metal. But if you have [MoltenVK](https://github.com/KhronosGroup/MoltenVK) installed you can use Vulkan instead...

```
cmake -S . -B build-macos-vulkan -GNinja \
  -DCMAKE_CXX_COMPILER_LAUNCHER=/opt/homebrew/bin/ccache \
  -DMLN_WITH_OPENGL=OFF \
  -DMLN_WITH_METAL=OFF \
  -DMLN_WITH_VULKAN=ON \
  -DMLN_LEGACY_RENDERER=OFF \
  -DMLN_DRAWABLE_RENDERER=ON \
  -DMLN_WITH_WERROR=OFF \
  -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
cmake --build build-macos-vulkan
build-macos-vulkan/platform/glfw/mbgl-glfw --style "https://tiles.openfreemap.org/styles/liberty"
```

**Pull request merged**
