### PR TITLE
Added design proposal for ambient cache initialization speed improvement

### PR DESCRIPTION
**Pull request by geolives**
Added design proposal for ambient cache initialization speed improvement to fix issue https://github.com/maplibre/maplibre-native/issues/1815

### CODE REVIEW

**Review by louwers — APPROVED** [review]
We're giving other community members some time to respond, but looks good to me. Thanks for writing it up.

**Comment by JesseCrocker** [comment]
Will the planned implementation of this support copying resources/tiles that exist in the cache tables to the download tables when a new download is created that uses them? A nice side effect of the current structure is that it avoids redownloading in that case. And if not will resources be deleted from the cache table if they are downloaded?

Did you consider putting the cache tables in a separate database, instead of just in new tables? In my experience a frequent cause of slowness when there are large downloads is db VACUUMing, and vacuuming tends to get triggered when there is lots of turnover in the cache table but the speed of vacuum depends on the overall size of the db.  It would also be nice to make clearing cache just be deleting a file instead of an sql `DELETE`.

**Comment by geolives** [comment]
Yes, when a new download is created that uses tiles / resources that are present in the ambient cache, we will move the data from the ambient cache tables to the offline data tables in order to avoid downloading it again.

For your other proposal of using two separate databases, it may be interesting to do that with a 2nd database attached to the main database connection via ATTACH DATABASE feature of SQLite.
The main drawback of using a second database is the performance to obtain data. 
We would have to query the two databases for each resource / tile, with a SELECT UNION query between the two tables in two different databases or with a SELECT in ambient cache table + a second SELECT in the offline table (in the other database) when the data is not present in the ambient cache.
What do you think about that?

It would be interesting to benchmark the performance in the two cases (all the data in the same database VS ambient cache in a second database).

We would suggest implementing it in two steps :

1st step : all the data in the same database

2nd step : ambient cache in a second database

Thank you.

**Review by louwers — CHANGES_REQUESTED** [review]
Please do the implementation to a different PR.

**Pull request closed without merging**
