### PR TITLE
Try to improve ccache usage Android

### PR DESCRIPTION
**Pull request by louwers**
I think ccache does not work well the way we are using it now. The render test app takes over an hour to build.

I hope this improves it.

### CODE REVIEW

**Comment by ntadej** [comment]
I see no explicit reason why this would help. I suspect the main build is just not using `ccache` correctly. Although now I see that some cache was built. Maybe we retry the pipeline and see if it's much faster now.

**Comment by louwers** [comment]
> Maybe we retry the pipeline and see if it's much faster now.

That's the plan :)

**Review by birkskyum — APPROVED** [review]

**Comment by louwers** [comment]
It's 15 minutes quicker the second, but could be a fluke.

**Review by mwilsnd — APPROVED** [review]

**Comment by louwers** [comment]
2h 25m 34s vs 75 minutes.

So I think it does something.

**Pull request merged**
