### PR TITLE
Request authorization to use location services has been made optional

### PR DESCRIPTION
**Pull request by alexcristici**
Added flag `shouldRequestAuthorizationToUseLocationServices` to control whether the framework should request authorization to use location services or not.

### CODE REVIEW

**Review by sjg-wdw — APPROVED** [review]
Look good.

**Review by cgalvan — APPROVED** [review]

**Comment by louwers** [comment]
Do you want to confirm this solves an issue before merging?

**Comment by sjg-wdw** [comment]
No one knows if this will solve the issue.  This will give them the opportunity to turn it off and deal with the issue at the app level.

**Comment by alexcristici** [comment]
I think this could be a good feature too, if the app wants to control in a custom way the location services request.

**Review by mwilsnd — APPROVED** [review]

**Pull request merged**
