### PR TITLE
[Windows] Update libwebp

### PR DESCRIPTION
**Pull request by mwilsnd**
Updates vcpkg to include `libwebp-1.3.2` which includes the OOB write fix.

### CODE REVIEW

**Review by louwers — APPROVED** [review]

**Comment by etnav** [comment]
@louwers Can we do a new Node release? The last release was back in March for [v5.2.0](https://github.com/maplibre/maplibre-native/releases/tag/node-v5.2.0)

**Comment by ntadej** [comment]
The problem is if we make it, it will not work on macOS.

**Comment by louwers** [comment]
@etnav I am not a Node.js maintainer. Maybe @acalcutt wants to look into it, but it would be a (breaking) pre-release first I think.

**Comment by etnav** [comment]
> @etnav I am not a Node.js maintainer. Maybe @acalcutt wants to look into it, but it would be a (breaking) pre-release first I think (without macOS support, unless we can get Metal to work already).

Understood, wasn't aware about the macOS part being "broken"!

**Pull request merged**
