### PR TITLE
Render Tests: fix icon texture filter type for symbol layer

### PR DESCRIPTION
**Pull request by stefankarschti**
Issue #1374

### CODE REVIEW

**Review by sjg-wdw — APPROVED** [review]

**Review by mwilsnd — APPROVED** [review]

**Comment by TimSylvester** [comment]
There may be a case where the atlases are shared between symbols that end up having different filtering results.  If so, this will make it work most of the time, but leave an edge case that we might not test for.

**Comment by mwilsnd** [comment]
Can different symbols from the same bucket evaluate such that both linear and nearest filtering is needed? The atlases are owned by the geometry tile render data so I don't _think_ there can be sharing outside of that scenario.

**Comment by TimSylvester** [comment]
It looks like all the variables either come from the bucket or apply to everything, so as long as buckets never share it should be fine.

**Comment by stefankarschti** [comment]
the assumption is that the drawables that need to use the atlases (especially icon, synce glyph is always set to linear by the legacy path) would set the sampler configuration in their drawable/layer tweakers before drawing. 
If the usage is serialized then it works, the issues arise with multi threaded rendering (which we don't have yet)...

**Review by TimSylvester — APPROVED** [review]

**Pull request merged**
