### PR TITLE
[node][opengl-2] Update node release based on maplibre-js release workflow - v2 with changelog

### PR DESCRIPTION
**Pull request by acalcutt**
This PR is a cherry pick of https://github.com/maplibre/maplibre-native/commit/43e52d054e234992ba030ffae3076b682d410324 which brings release workflow updates from https://github.com/maplibre/maplibre-native/pull/1995 into the 'opengl-2'

My goal is to create at least one more release (and pre-release) from the 'opengl-2' branch, which supports node 20 and macos

The only change I made other than the cherry pick was to update this to run on `branches: [opengl-2]` and to re-enable the macos in the workflow.

### CODE REVIEW

**Comment by ntadej** [comment]
What should we do with the failing ARM test? I guess you need it for the release?

**Comment by acalcutt** [comment]
For the arm releases, the binary is buiding but some of the tests are failing. So I was considering doing a pre-release and asking someone i know on macos to try it out. these tests have never been 100% on all platforms.

I was looking at the failed tests in https://github.com/maplibre/maplibre-native/pull/1942 . you can see how they are failing in the results at https://github.com/maplibre/maplibre-native/actions/runs/7183103165?pr=1942 . Some of the failing tests have been disable in the main branch, although the ones left seems like it is failing some type of calculation slightly.

most of the tests the failed visually don't looks that off, so I am unsure if it is a test issue or a build issue.

**Comment by acalcutt** [comment]
We only usually run these tests on macos, but in that test PR I enabled them in linux too and one thing i notices is the arm64 linux version fails in a similar way with some type of lat/lon calculation slightly off. At least for that release, i can test a bit more myself once we have a pre-release of it, since I usually use the arm64 linux version locally.

**Review by louwers — APPROVED** [review]

**Comment by louwers** [comment]
Approved based on the fact that it is a cherry-pick so already approved.

**Comment by acalcutt** [comment]
@louwers Any suggestion on what I should do about the required test that isn't running required to merge this?

It looks like maybe the qt-ci build it is requiring, but it doesn't seem like it triggered. looking at that qt-ci it is set to run on this branch, so not sure what it didn't run like the node tests.

**Comment by ntadej** [comment]
You can ignore that. I can merge it but I wonder if failing ARM test still allows you to make a release?

**Comment by acalcutt** [comment]
yes, even with the failing arm test it would still allow a release. the release doesn't run any tests, it just builds the binary and posts it to github and publishes the npm. We can see from the tests that the build portion of this works, so that should succeed.

To publish a release I would create a new PR to change the version and CHANGELOG in this branch, like https://github.com/maplibre/maplibre-native/pull/2005/files#diff-98b4dc8f37a6a0ef8854dd55234f64ea248f90654c4027ee3fdba48e9b14a30a

**Pull request merged**
