### PR TITLE
Annotation view recycling re-enabled

### PR DESCRIPTION
**Pull request by alexcristici**
Reverted code that disabled annotation view recycling, from this PR: https://github.com/maplibre/maplibre-native/pull/2148.
We don't need that workaround after fixing the `presentsWithTransaction` rendering in this PR: https://github.com/maplibre/maplibre-native/pull/2442.

Before `presentsWithTransaction` fix:

https://github.com/maplibre/maplibre-native/assets/19795769/e858aedc-520b-469b-9671-b5833faf7d6e

After `presentsWithTransaction` fix:

https://github.com/maplibre/maplibre-native/assets/19795769/0d6b8e9a-0a17-4b2d-967b-609a88c65b25

### CODE REVIEW

**Review by sjg-wdw — APPROVED** [review]
Can we prove that this still fixes the original bug?

**Comment by alexcristici** [comment]
I tested on my side and it fixes.

**Comment by sjg-wdw** [comment]
Works for me

**Review by mwilsnd — APPROVED** [review]

**Comment by alexcristici** [comment]
I added some screen recording.

**Review by cgalvan — APPROVED** [review]

**Review by louwers — APPROVED** [review]

**Pull request merged**
