### PR TITLE
Add ankerl::unordered_dense containers

### PR DESCRIPTION
**Pull request by mwilsnd**
Add `ankerl::unordered_dense` containers as a default build option, replacing std containers in various hot-paths. This yields a notable performance improvement on Android and Windows platforms.

### CODE REVIEW

**Comment by mwilsnd** [comment]
@ntadej @louwers I think its time to retire GCC 8. Ran into what appears to be a defect in `std::pmr` with GCC 8 alone - trying to use `dynamic_cast` when RTTI is off. See [this run](https://github.com/maplibre/maplibre-native/actions/runs/6948394481/job/18904296023).

No other compilers tested (MSVC 17 2022, Clang 11, 14, GCC 10, 12) show the same defect. I've temporarily forked this library to not try and include PMR if RTTI is off but before this is merged I want my temporary fork reverted.

**Comment by ntadej** [comment]
Which platform is that?

**Comment by mwilsnd** [comment]
Looks like Ubuntu.

**Comment by ntadej** [comment]
Can you just revert the fork then? I'll have a look and probably then we can either try to update the compiler or disable the test.

**Comment by mwilsnd** [comment]
I've reverted the fork modification that addressed GCC 8.

**Comment by ntadej** [comment]
Can you please try updating `.github/actions/qt5-build/Dockerfile` and set the image to `FROM ghcr.io/maplibre/linux-builder:centos8-latest`? I think this should fix it. I can later prepare an image with older CMake version so we have sufficient test coverage.

**Comment by mwilsnd** [comment]
Changed the image but no dice. I think as long as GCC 8 is trying to build this the workflow will fail.

**Comment by ntadej** [comment]
Hmm, I thought this image has a newer compiler. Let me update it tomorrow.

**Comment by ntadej** [comment]
You can rebase now.

**Comment by mwilsnd** [comment]
Awesome! Thanks for taking a look.

**Review by sjg-wdw — APPROVED** [review]

**Review by TimSylvester — APPROVED** [review]

**Review by alexcristici — APPROVED** [review]

**Review by stefankarschti — APPROVED** [review]

**Pull request merged**
