### PR TITLE
Use C++20

### PR DESCRIPTION
**Pull request by louwers**
Update build config CMake and Bazel to use C++20.

C++20 brings many features and improvements. Here are some links.

- https://github.com/AnthonyCalandra/modern-cpp-features/blob/master/CPP20.md
- https://en.cppreference.com/w/cpp/compiler_support#cpp20

Getting CI to pass needed a few changes.

- [x] Fix some new errors due to uninitialized data members.
- [x] Change to `CMakeLists.txt` to suppress an error due to an gcc compiler bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105651
- [x] Add casts to Objective-C++ in argument to `CGImageCreate`
- [x] Fix ambiguity in `FormatSectionOverride::operator==` due to the fact that the compiler can rewrite (reverse) it now.
- [x] Fix lambdas that capture `this` implicitly.
- [x] Rewrite some `EXPECT_EQ(x, y)` to `EXPECT_TRUE(x == y)` in the unit tests, because the former uses `std::to_chars` in when comparing timestamps, but that function is only available in recent iOS versions.
- [x] Rewrite some `x.count(y) != 0` to `x.contains(y)` (clang error).

### CODE REVIEW

**Comment by louwers** [comment]
Getting a bunch of these:

```
/app/test/style/property_expression.test.cpp:204:32: error: ISO C++20 considers use of overloaded operator '!=' (with operand types 'mbgl::style::expression::FormatSectionOverride<mbgl::Color>' and 'mbgl::style::expression::FormatSectionOverride<mbgl::Color>') to be ambiguous despite there being a unique best viable function [clang-diagnostic-ambiguous-reversed-operator,-warnings-as-errors]
        EXPECT_TRUE(*override1 != *override2);
                               ^
/app/vendor/googletest/googletest/include/gtest/gtest.h:1786:50: note: expanded from macro 'EXPECT_TRUE'
#define EXPECT_TRUE(condition) GTEST_EXPECT_TRUE(condition)
                                                 ^~~~~~~~~
/app/vendor/googletest/googletest/include/gtest/gtest.h:1771:23: note: expanded from macro 'GTEST_EXPECT_TRUE'
  GTEST_TEST_BOOLEAN_(condition, #condition, false, true, \
                      ^~~~~~~~~
/app/vendor/googletest/googletest/include/gtest/internal/gtest-internal.h:1504:38: note: expanded from macro 'GTEST_TEST_BOOLEAN_'
          ::testing::AssertionResult(expression))                     \
                                     ^~~~~~~~~~
/app/include/mbgl/style/expression/format_section_override.hpp:38:10: note: ambiguity is between a regular call to this operator and a call with the argument order reversed
    bool operator==(const Expression& e) const final {
         ^
```

**Comment by louwers** [comment]
gcc-12 maybe uninitialized

```
In file included from /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:16,
                 from /app/include/mbgl/util/variant.hpp:8,
                 from /app/include/mbgl/style/expression/type.hpp:4,
                 from /app/include/mbgl/style/expression/parsing_context.hpp:4,
                 from /app/src/mbgl/style/expression/parsing_context.cpp:2:
In destructor 'mapbox::util::recursive_wrapper<T>::~recursive_wrapper() [with T = mbgl::style::expression::type::Array]',
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>; Types = {mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:250:43,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::ValueType; Types = {mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:254:46,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::ValueType; Types = {mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:246:32,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::ObjectType; Types = {mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:254:46,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::ObjectType; Types = {mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:246:32,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::ColorType; Types = {mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:254:46,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::ColorType; Types = {mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:246:32,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::StringType; Types = {mbgl::style::expression::type::ColorType, mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:254:46,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::StringType; Types = {mbgl::style::expression::type::ColorType, mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:246:32,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::BooleanType; Types = {mbgl::style::expression::type::StringType, mbgl::style::expression::type::ColorType, mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:254:46,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::BooleanType; Types = {mbgl::style::expression::type::StringType, mbgl::style::expression::type::ColorType, mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:246:32,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::NumberType; Types = {mbgl::style::expression::type::BooleanType, mbgl::style::expression::type::StringType, mbgl::style::expression::type::ColorType, mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:254:46,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::NumberType; Types = {mbgl::style::expression::type::BooleanType, mbgl::style::expression::type::StringType, mbgl::style::expression::type::ColorType, mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:246:32,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::NullType; Types = {mbgl::style::expression::type::NumberType, mbgl::style::expression::type::BooleanType, mbgl::style::expression::type::StringType, mbgl::style::expression::type::ColorType, mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:254:46,
    inlined from 'static void mapbox::util::detail::variant_helper<T, Types ...>::destroy(mapbox::util::type_index_t, void*) [with T = mbgl::style::expression::type::NullType; Types = {mbgl::style::expression::type::NumberType, mbgl::style::expression::type::BooleanType, mbgl::style::expression::type::StringType, mbgl::style::expression::type::ColorType, mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:246:32,
    inlined from 'mapbox::util::variant<Types>::~variant() [with Types = {mbgl::style::expression::type::NullType, mbgl::style::expression::type::NumberType, mbgl::style::expression::type::BooleanType, mbgl::style::expression::type::StringType, mbgl::style::expression::type::ColorType, mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType}]' at /app/vendor/mapbox-base/deps/variant/include/mapbox/variant.hpp:875:29,
    inlined from 'mbgl::style::expression::ParseResult mbgl::style::expression::ParsingContext::parse(const mbgl::style::conversion::Convertible&, const std::optional<mbgl::style::expression::TypeAnnotationOption>&)' at /app/src/mbgl/style/expression/parsing_context.cpp:240:5:
/app/vendor/mapbox-base/deps/variant/include/mapbox/recursive_wrapper.hpp:47:44: warning: '*(mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>*)((char*)&type + offsetof(const mapbox::util::Type, mapbox::util::variant<mbgl::style::expression::type::NullType, mbgl::style::expression::type::NumberType, mbgl::style::expression::type::BooleanType, mbgl::style::expression::type::StringType, mbgl::style::expression::type::ColorType, mbgl::style::expression::type::ObjectType, mbgl::style::expression::type::ValueType, mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>, mbgl::style::expression::type::CollatorType, mbgl::style::expression::type::FormattedType, mbgl::style::expression::type::ErrorType, mbgl::style::expression::type::ImageType>::data)).mapbox::util::recursive_wrapper<mbgl::style::expression::type::Array>::p_' may be used uninitialized [-Wmaybe-uninitialized]
   47 |     ~recursive_wrapper() noexcept { delete p_; }
      |                                            ^~
/app/src/mbgl/style/expression/parsing_context.cpp: In member function 'mbgl::style::expression::ParseResult mbgl::style::expression::ParsingContext::parse(const mbgl::style::conversion::Convertible&, const std::optional<mbgl::style::expression::TypeAnnotationOption>&)':
/app/src/mbgl/style/expression/parsing_context.cpp:231:26: note: 'type' declared here
  231 |         const type::Type type = (*parsed)->getType();
      |                          ^~~~
```

**Comment by louwers** [comment]
Screenshot 2024-08-09 at 13 58 25
Null pointer dereference

**Comment by stefankarschti** [comment]
> Screenshot 2024-08-09 at 13 58 25 Null pointer dereference, but somehow only a single frame available in the debugger.

Could be stack corruption. 
But generally how about moving away completely from `mapbox::util::variant` and replace with `std::variant`?

**Comment by louwers** [comment]
@stefankarschti I updated my comment. Yes that is the plan!

**Comment by ntadej** [comment]
Did Qt just build out of the box?

**Comment by louwers** [comment]
@ntadej On macOS the unit tests did not compile similar to iOS. But otherwise yes.

**Review by birkskyum — APPROVED** [review]

**Review by ntadej — APPROVED** [review]

**Pull request merged**
