### PR TITLE
[qt] Try to stabilise the CI

### LINKED ISSUE #2118: Qt workflow failing:  404  Not Found
https://github.com/maplibre/maplibre-native/actions/runs/7931770057/job/21659977297?pr=1908

There's an issue downloading dependencies on Ubuntu with the Qt workflow.

> E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_23.0.4-0ubuntu1%7e22.04.1_amd64.deb  404  Not Found [IP: 20.106.104.242 80]

@ntadej If you have time, maybe you could have a look.

### PR DESCRIPTION
**Pull request by ntadej**
- Update to Qt 6.6.2
- Use a better mirror
- Always run `apt-get update`
- Use newer macOS runners

Fixes #2118.

### CODE REVIEW

**Review by HarelM — APPROVED** [review]

**Comment by ntadej** [comment]
@louwers, it seems actionlint needs an update but we'd benefit from faster runners. How should we proceed?

**Comment by louwers** [comment]
Let me fix it.

**Comment by louwers** [comment]
Once actionlint has a new release this fix can be removed. https://github.com/rhysd/actionlint/issues/393

**Comment by ntadej** [comment]
Ah, did not spot we already have this config file. Thanks!

**Pull request merged**
