### PR TITLE
Release node v6.0.1-pre.0

### PR DESCRIPTION
**Pull request by acalcutt**
This PR makes a node pre release with `textFitWidth` and `textFitHeight` included.

I looked through the other PRs and wonder if any of them should be included in the changelog. Like,
Fix raster masking bug https://github.com/maplibre/maplibre-native/pull/2798

### CODE REVIEW

**Review by louwers — APPROVED** [review]
I tend to make pre-releases from main.

**Comment by louwers** [comment]
Oh I don't make new branches for releases.

**Comment by acalcutt** [comment]
Do you mind if I add a few changes to the node README. I noticed at the bottom of https://www.npmjs.com/package/@maplibre/maplibre-gl-native that the relative link to https://github.com/maplibre/maplibre-native/blob/main/platform/node/DEVELOPING.md does not work. I just want to replace this with the full url path so it works on the npm site.

I also may go through that DEVELOPING.md and add some updates.

**Comment by louwers** [comment]
Sure!

**Review by louwers — APPROVED** [review]

**Comment by acalcutt** [comment]
@louwers I am done with this I think. I was originally going to update the PUBLISHING section, but I decided to just make it a link to RELEASE.md, do you think that is fine or was it better the other way? It seemed like duplicate information.

**Comment by louwers** [comment]
Sounds good.

**Pull request merged**
