### PR TITLE
Tiny map

### PR DESCRIPTION
**Pull request by TimSylvester**
Finally getting close to something usable, I think.

Using fixed, contiguous storage for keys and values in the class for small key sets and falling back on `unordered_map` for  everything else works well, with a good choice of fixed size.

I still don't see any benefit for 64-bit ints, I expect because hashing them is nearly free and they're just generally very efficient.

```
                                     2    4     6     8     10    12    14    16
                                     -------------------------------------------
int:stl    threshold=000 (x 2):      6    12    17    22    27    34    38    43    49    56
int:tiny   threshold=004 (x 2):      5    11    17    22    28    33    39    44    52    54
int:tiny   threshold=008 (x 2):      5    12    21    26    28    33    38    43    49    55
int:tiny   threshold=016 (x 2):      5    12    18    27    38    50    64    79    49    56

                                     1     2     3     4   5     6     7     8
                                     -------------------------------------------
str:stl    threshold=000 (x 1):     25    41    95    83   153   180   210   166   279   305
str:tiny   threshold=004 (x 1):     12*   28*   51*   82   172   209   245   215   335   349
str:tiny   threshold=008 (x 1):     12*   28*   51*   81   119   163   245   305   326   346
str:tiny   threshold=016 (x 1):     12*   28*   51*   83   125   171   243   317   387   471

                                     2    4     6     8     10   12    14    16
                                     -------------------------------------------
tile:stl   threshold=000 (x 2):     16    29    52    57    89   114   116   112   158   178
tile:tiny  threshold=004 (x 2):      6*   18*   53    58    91   118   117   113   162   180
tile:tiny  threshold=008 (x 2):      6*   21*   32*   47*   91   120   117   114   161   183
tile:tiny  threshold=016 (x 2):      6*   21*   32*   47*   70*   99*  129   159   159   179
```

And from the Linux machine:
```
int:stl    threshold=000 (x 2):      9    19    27    37    46    55    65    76   135    91
int:tiny   threshold=004 (x 2):     10    18    29    38    46    56    64    73    82    91
int:tiny   threshold=008 (x 2):      8    14    25    44    49    59    64    73    83    96
int:tiny   threshold=016 (x 2):     10    19    31    42    58    72    90   108    90    99

str:stl    threshold=000 (x 1):      8    21    33    52    80   104   152   193   227   275
str:tiny   threshold=004 (x 1):      8    22    39    56    94   127   165   215   244   301
str:tiny   threshold=008 (x 1):      8    20    32    51    74   102   128   164   250   291
str:tiny   threshold=016 (x 1):      8    19    36    52    84   115   146   176   200   233

tile:stl   threshold=000 (x 2):     38    62    93   128   164   219   199   241   281   309
tile:tiny  threshold=004 (x 2):     10    18    97   131   162   238   201   245   280   307
tile:tiny  threshold=008 (x 2):     10    18    39    62   165   219   200   246   275   308
tile:tiny  threshold=016 (x 2):     11    23    36    68    86   121   160   179   277   312
```

### CODE REVIEW

**Comment by sjg-wdw** [comment]
That's a bit disappointing.  Curious to see what you find here.

**Review by stefankarschti — APPROVED** [review]
I think this is a good addition to `util::` as we could easy swap it in place of any current  `unordered_map` or `map` to test for potential improvement, especially where the number of elements is small enough.

**Comment by stefankarschti** [comment]
> Finally getting close to something usable, I think.
> 
> Using fixed, contiguous storage for keys and values in the class for small key sets and falling back on `unordered_map` for everything else works well, with a good choice of fixed size.
> 
> I still don't see any benefit for 64-bit ints, I expect because hashing them is nearly free and they're just generally very efficient.
> 
> ```
>                                      2    4     6     8     10    12    14    16
>                                      -------------------------------------------
> int:stl    threshold=000 (x 2):      6    12    17    22    27    34    38    43    49    56
> int:tiny   threshold=004 (x 2):      5    11    17    22    28    33    39    44    52    54
> int:tiny   threshold=008 (x 2):      5    12    21    26    28    33    38    43    49    55
> int:tiny   threshold=016 (x 2):      5    12    18    27    38    50    64    79    49    56
> 
>                                      1     2     3     4   5     6     7     8
>                                      -------------------------------------------
> str:stl    threshold=000 (x 1):     25    41    95    83   153   180   210   166   279   305
> str:tiny   threshold=004 (x 1):     12*   28*   51*   82   172   209   245   215   335   349
> str:tiny   threshold=008 (x 1):     12*   28*   51*   81   119   163   245   305   326   346
> str:tiny   threshold=016 (x 1):     12*   28*   51*   83   125   171   243   317   387   471
> 
>                                      2    4     6     8     10   12    14    16
>                                      -------------------------------------------
> tile:stl   threshold=000 (x 2):     16    29    52    57    89   114   116   112   158   178
> tile:tiny  threshold=004 (x 2):      6*   18*   53    58    91   118   117   113   162   180
> tile:tiny  threshold=008 (x 2):      6*   21*   32*   47*   91   120   117   114   161   183
> tile:tiny  threshold=016 (x 2):      6*   21*   32*   47*   70*   99*  129   159   159   179
> ```
> 
> And from the Linux machine:
> 
> ```
> int:stl    threshold=000 (x 2):      9    19    27    37    46    55    65    76   135    91
> int:tiny   threshold=004 (x 2):     10    18    29    38    46    56    64    73    82    91
> int:tiny   threshold=008 (x 2):      8    14    25    44    49    59    64    73    83    96
> int:tiny   threshold=016 (x 2):     10    19    31    42    58    72    90   108    90    99
> 
> str:stl    threshold=000 (x 1):      8    21    33    52    80   104   152   193   227   275
> str:tiny   threshold=004 (x 1):      8    22    39    56    94   127   165   215   244   301
> str:tiny   threshold=008 (x 1):      8    20    32    51    74   102   128   164   250   291
> str:tiny   threshold=016 (x 1):      8    19    36    52    84   115   146   176   200   233
> 
> tile:stl   threshold=000 (x 2):     38    62    93   128   164   219   199   241   281   309
> tile:tiny  threshold=004 (x 2):     10    18    97   131   162   238   201   245   280   307
> tile:tiny  threshold=008 (x 2):     10    18    39    62   165   219   200   246   275   308
> tile:tiny  threshold=016 (x 2):     11    23    36    68    86   121   160   179   277   312
> ```

What are the units used, how to read the graph?

**Comment by TimSylvester** [comment]
The numbers are microseconds for an create/lookup cycle with 100 lookups, but it's mostly the relative values that's relevant.  Each column represents more items being added and then looked up.  Create and lookup are done in a random order.  I put a `*` where it's a win.

The code is in `test/util/tiny_map.test.cpp` if you want to see exactly what's done.

**Pull request merged**
