### PR TITLE
Update vcpkg to ac68eb6

### PR DESCRIPTION
**Pull request by mwilsnd**
Fixes missing msys2 packages

### CODE REVIEW

**Comment by mwilsnd** [comment]
Can someone confirm if libuv links correctly for them? `uv_a` no longer links on my machines after updating vcpkg and instead resolves to just `uv`. I updated the CMake following usage output from vcpkg but CI isn't resolving it correctly and I'm not sure why.

**Comment by louwers** [comment]
cc @tdcosta100

**Comment by tdcosta100** [comment]
Sorry for taking so long to answer. I've been busy these days. So @mwilsnd, you are trying to update `vcpkg` to 2023.06.20, but the current reference to `vcpkg` points to a commit in 2023.06.21, that is, you are proposing a downgrade. Maybe when you created this branch, `vcpkg` wasn't updated yet? Anyway, there is a important fix in the 2023.06.21 version, so maybe you could try a newer commit, not necessarily a release tag.

**Comment by mwilsnd** [comment]
I didn't notice the release was detached from a tag - that would explain some things. I'll try updating it to a newer commit that makes some changes to libuv's target name.

**Comment by tdcosta100** [comment]
Okay, but it's strange, I'm not having any trouble with libuv at all. Did you tried to delete the vcpkg database located at ? 
`%LOCALAPPDATA%\vcpkg`?

**Comment by mwilsnd** [comment]
The issue was on CI, which I see now got unintentionally reverted on the drawables development branch - explaining even more things. I'm going to re-target this PR on that branch and keep main as-is for the moment.

**Review by TimSylvester — APPROVED** [review]
Still builds fine under Xcode, for whatever that's worth.

**Pull request merged**
