### PR TITLE
Do not run tests for glInvalidateFramebuffer & glInvalidateSubFramebuffer on macOS

### PR DESCRIPTION
**Pull request by SiarheiFedartsou**
They are available only on iOS and iOS Simulator if current platform is Darwin https://github.com/maplibre/maplibre-native/blob/f8c2c6c8b3f1fce6a3529b240d4d3c695a5edfb1/platform/darwin/src/gl_functions.cpp#L268. That's why locally I have such linker errors(for `cmake .. && make -j8 mbgl-test-runner`):
Screenshot 2023-05-06 at 12 47 15

Not sure why it is green on existing macOS CI...

### CODE REVIEW

**Comment by ntadej** [comment]
Darwin is currently not really supported on `main` due to OpenGL ES 3 migration. We do not even run the CI.

**Comment by SiarheiFedartsou** [comment]
> Darwin is currently not really supported on `main` due to OpenGL ES 3 migration. We do not even run the CI.

Hm, indeed, I got confused by presence of https://github.com/maplibre/maplibre-native/blob/f8c2c6c8b3f1fce6a3529b240d4d3c695a5edfb1/.github/workflows/macos-ci.yml#L3. But there are people like me who work on macOS 😄

**Comment by ntadej** [comment]
That's why I maintain `opengl-2` branch.

**Comment by louwers** [comment]
macOS now support Metal (and Vulkan via MoltenVK).

**Pull request closed without merging**
